machine:
  services:
    - docker

test:
  override:
    - docker build -t ci-cd-test .
    - docker run -p 5001 -d ci-cd-test:latest

deployment:
  hub:
    branch: master
    commands:
      - $DEPLOY