version: 2
jobs:
    build:
      machine: true 
      steps:
        - checkout
        - run: docker build -t adnanrajput/ci-cd-test:latest .
        - run:
            name: Push to DockerHub
            command: |
              docker login -u $DOCKER_USER ---password-stdin $DOCKER_PASS
              $DEPLOY
