version: 2
jobs:
  build:
    docker:
      image: alpine
  steps:
    - run:
         name: Build Docker image
         command: docker build -t ci-cd-test:latest .

  deployment:
    hub:
      branch: master
      commands:
        - $DEPLOY