version: 2
jobs:
    build:
      machine: true 
      steps:
        - checkout
        - run: docker build -t adnanrajput/ci-cd-test:v1 .
        - run:
            name: Push to DockerHub
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push adnanrajput/ci-cd-test:v1
