machine:
  services:
    - docker
  jobs:
    build:
      steps:
        - run: 
          - docker build -t test:latest .

  deployment:
    hub:
      branch: master
      commands:
        - $DEPLOY