version: 2
jobs:
    build:
      steps:
        - checkout
        - setup_remote_docker: 
            docker_layer_caching: true 
        - run: docker build -t company/app:$CIRCLE_BRANCH .
        - run: $DEPLOY
